# Application
spring.application.name=location-service
server.port=8082

server.servlet.context-path=/api

# Redis COnfiguration
spring.data.redis.host=localhost
spring.data.redis.port=6379

# Actuator
management.endpoints.web.exposure.include[0]=health
management.endpoints.web.exposure.include[1]=info